superfeedr: fix minor logging bug with unicode chars in content
requests were succeeding, but we got this stacktrace in logs instead of the content:

```
Traceback (most recent call last):
  File ".../python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File ".../python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File ".../python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File ".../python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 37: ordinal not in range(128)
Logged from file superfeedr.py, line 76
```