try to fix a flaky test by adding import appengine_config lines
specifically this, only on circle, e.g. https://circleci.com/gh/snarfed/bridgy/740 :

```
FAIL: test_connection_failures_503 (test.test_handlers.HandlersTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/project/local/lib/python2.7/site-packages/mox3/mox.py", line 2139, in new_method
    func(self, *args, **kwargs)
  File "/root/project/test/test_handlers.py", line 185, in test_connection_failures_503
    resp = self.check_response('/post/fake/%s/000', expected_status=504)
  File "/root/project/test/test_handlers.py", line 62, in check_response
    '%s %s' % (resp.status_int, html))
AssertionError: 500 500 Internal Server Error

The server has either erred or is incapable of performing the requested operation.
```

not sure of the underlying cause yet.