instagram: nice error when we can't fetch their site for indieauth
e.g.:

```
2018-01-04 05:33:28.750 WET
encoding state "{'callback': u'https://xavierroy.com/wp-admin/admin.php?page=bridgy_options&service=instagram', 'operation': 'add', 'user_url': u'https://xavierroy.com', 'feature': u'listen,publish', 'id': ''}" (local/lib/python2.7/site-packages/oauth_dropins/webutil/util.py:807)
2018-01-04 05:33:28.750 WET
requests.get https://xavierroy.com {} (local/lib/python2.7/site-packages/oauth_dropins/webutil/util.py:1188)
2018-01-04 05:33:28.861 WET
Invalid and/or missing SSL certificate for URL: https://xavierroy.com/ (...python27_lib/versions/third_party/webapp2-2.3/webapp2.py:1528)
Traceback (most recent call last):
...
  File "instagram.py", line 118, in post
    self.redirect(ia_start.redirect_url(me=util.get_required_param(self, 'user_url')))
  File "util.py", line 539, in redirect_url
    self.construct_state_param_for_add(state, **kwargs), **ru_kwargs)
  File "local/lib/python2.7/site-packages/oauth_dropins/indieauth.py", line 123, in redirect_url
    endpoint = discover_authorization_endpoint(me)
  File "local/lib/python2.7/site-packages/oauth_dropins/indieauth.py", line 37, in discover_authorization_endpoint
    resp = resp or util.requests_get(me)
  File "local/lib/python2.7/site-packages/oauth_dropins/webutil/util.py", line 1191, in call
    return getattr(requests, fn)(url, *args, **kwargs)
  File "local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "local/lib/python2.7/site-packages/requests/adapters.py", line 519, in send
    raise SSLError(e, request=request)
SSLError: Invalid and/or missing SSL certificate for URL: https://xavierroy.com/
```