twitter: interpret 404s from the API as transient errors
```
urlopen GET https://api.twitter.com/1.1/statuses/user_timeline.json?include_entities=true&tweet_mode=extended&count=50&screen_name= {} (/base/data/home/apps/s~brid-gy/background:8.420337248316607855/local/lib/python2.7/site-packages/oauth_dropins/webutil/util.py:1316)
Error 404, response body: u'{"errors":[{"code":34,"message":"Sorry, that page does not exist."}]}' (/base/data/home/apps/s~brid-gy/background:8.420337248316607855/local/lib/python2.7/site-packages/oauth_dropins/webutil/util.py:1107)
HTTP Error 404: Not Found (/base/data/home/apps/s~brid-gy/background:8.420337248316607855/local/lib/python2.7/site-packages/webapp2.py:1590)
Traceback (most recent call last):
...
  File "/base/data/home/apps/s~brid-gy/background:8.420337248316607855/tasks.py", line 95, in post
    self.poll(source)
  File "/base/data/home/apps/s~brid-gy/background:8.420337248316607855/tasks.py", line 161, in poll
    min_id=source.last_activity_id, cache=cache)
  File "/base/data/home/apps/s~brid-gy/background:8.420337248316607855/models.py", line 348, in get_activities_response
    resp = self.gr_source.get_activities_response(**kwargs)
  File "/base/data/home/apps/s~brid-gy/background:8.420337248316607855/local/lib/python2.7/site-packages/granary/twitter.py", line 299, in get_activities_response
    resp = self.urlopen(url, headers=headers, parse_response=False)
  File "/base/data/home/apps/s~brid-gy/background:8.420337248316607855/local/lib/python2.7/site-packages/granary/twitter.py", line 1093, in urlopen
    return request()
  File "/base/data/home/apps/s~brid-gy/background:8.420337248316607855/local/lib/python2.7/site-packages/granary/twitter.py", line 1085, in request
    url, self.access_token_key, self.access_token_secret, **kwargs)
...
HTTPError: HTTP Error 404: Not Found
```